# Generated by Django 3.1.5 on 2021-01-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('postby', models.CharField(max_length=100)),
            ],
        ),
    ]
