# Generated by Django 3.1.5 on 2021-01-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prac',
            name='com',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prac',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
