# Generated by Django 3.1.5 on 2021-04-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20210124_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='prac',
            name='dest',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
