# Generated by Django 3.1.5 on 2021-04-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_prac_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='prac',
            name='discription',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
